version: '3'
services:
#  api:
#    container_name: "gotube_data"
#    build: .
#    ports:
#      - ${APP_PORT}:${APP_PORT}
#    restart: on-failure
#    volumes:
#      - api:/usr/src/app/
#    depends_on:
#      - fullstack-mysql
#      - redis
#    networks:
#      - fullstack


  fullstack-mysql:
    image: mysql:8.0
    container_name: gotube_db
    ports: 
      - ${DB_PORT}:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack

  redis:
    image: "redis:alpine"
    container_name: ${REDIS_HOST}
    command: redis-server --requirepass ${REDIS_PASSWORD}

    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

    networks:
      - fullstack


volumes:
  api:
  database_mysql:                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge